/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: "class",
    content: ["./src/**/*.{js,jsx,ts,tsx}"],
    safelist: [
        {
            pattern:
                /^text-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-800$/,
        },
    ],
    plugins: [require("@tailwindcss/line-clamp")],
    theme: {
        extend: {
            keyframes: {
                flash: {
                    "0%, 100%": { backgroundColor: "transparent" },
                    "50%": { backgroundColor: "#d1fae5" }, // light green
                },
            },
            animation: {
                "flash-once": "flash 1s ease-in-out",
            },

            colors: {
                gb: {
                    bg: "#1e1e1e",
                    fg: "#ebdbb2",
                    red: "#fb4934",
                    green: "#b8bb26",
                    yellow: "#fabd2f",
                    blue: "#83a598",
                    purple: "#d3869b",
                    aqua: "#8ec07c",
                    orange: "#fe8019",
                    gray: "#3c3836",
                    comment: "#928374",
                },
                mt: {
                    bg: "#222526",
                    fg: "#d4be98",
                    cyan: "#89b482",
                    black: "#665c54",
                    gray: "#504945",
                    magenta: "#d3869b",
                    red: "#ea6962",
                    green: "#a9b665",
                    yellow: "#d8a657",
                    blue: "#7daea3",
                    orange: "#e78a4e",
                    black: "#928374",
                },
                hmt: {
                    light: {
                        red: "#ea6962",
                        orange: "#e78a4e",
                        yellow: "#d8a657",
                        green: "#a9b665",
                        aqua: "#89b482",
                        blue: "#7daea3",
                        purple: "#d3869b",
                        black: "#5a524c",
                        white: "#d4be98",
                        softContrast: "#f2e5bc",
                        default: "#fbf1c7",
                        hardContrast: "#f9f5d7",
                        option2: "#d5c4a1",
                        option3: "#bdae93",
                        option4: "#a89984",
                    },
                    dark: {
                        red: "#c14a4a",
                        orange: "#c35e0a",
                        yellow: "#b47109",
                        green: "#6c782e",
                        aqua: "#4c7a5d",
                        blue: "#45707a",
                        purple: "#945e80",
                        black: "#c9b99a",
                        white: "#654735",
                        softContrast: "#32302f",
                        default: "#282828",
                        hardContrast: "#1d2021",
                        option2: "#504945",
                        option3: "#665c54",
                        option4: "#7c6f64",
                    },
                },
                hmx: {
                    light: {
                        red: "#f2594b",
                        orange: "#f28534",
                        yellow: "#e9b143",
                        green: "#b0b846",
                        aqua: "#8bba7f",
                        blue: "#80aa9e",
                        purple: "#d3869b",
                        black: "#5a524c",
                        white: "#e2cca9",
                        softContrast: "#f2e5bc",
                        default: "#fbf1c7",
                        hardContrast: "#f9f5d7",
                        option2: "#d5c4a1",
                        option3: "#bdae93",
                        option4: "#a89984",
                    },
                    dark: {
                        red: "#af2528",
                        orange: "#b94c07",
                        yellow: "#b4730e",
                        green: "#72761e",
                        aqua: "#477a5b",
                        blue: "#266b79",
                        purple: "#924f79",
                        black: "#c9b99a",
                        white: "#514036",
                        softContrast: "#32302f",
                        default: "#282828",
                        hardContrast: "#1d2021",
                        option2: "#504945",
                        option3: "#665c54",
                        option4: "#7c6f64",
                    },
                },
                my: {
                    bg: "#2F3438",
                    bg2: "#2B2C2E",
                    red: "#F15A51",
                    lime: "#B3B74F",
                    yellow: "#E9B050",
                    blue: "#799F95",
                    pink: "#D3879B",
                    green: "#8DB982",
                    fg: "#E1CDAC",
                },
                "my-lt": {
                    bg: "#EBE6D2",
                    bg2: "#C8B99C",
                    red: "#AE272D",
                    lime: "#767324",
                    yellow: "#CF974D",
                    blue: "#296C77",
                    pink: "#905078",
                    green: "#48795C",
                    fg: "#513C38",
                },
            },
        },
    },
};
