name: Hello World Workflow

on: push

jobs:
  build:
    # Run on raspberry-pi runner
    runs-on: arc-sequence-builder
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: chloesk/sequence-builder-backend:0.0.4
