name: Hello World Workflow

on: push

jobs:
  build:
    # Run on raspberry-pi runner
    runs-on: arc-sequence-builder
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
