name: ci

on:
  push:
    tags:
      - '*' # This wild card matches any tag

jobs:
  build:
    runs-on: arc-sequence-builder-frontend
    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Push container to docker
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: chloesk/sequence-builder-frontend:0.0.4
